services:
  redis:
    image: redis/redis-stack:latest
    container_name: employee-redis
    ports:
      - "6379:6379" # Default Redis port
      - "8001:8001" # For RedisInsight UI (optional, but very useful)
    environment:
      - "REDIS_ARGS: --save 60 1 --appendonly yes" # Basic persistence config
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "INFO"]
      interval: 10s
      timeout: 5s
      retries: 5